### ISSUE TITLE
Crashes AnkiDroid

### ISSUE THREAD

**Issue by leezu** [badlydrawnrob/anki#17]
Hey badlydrawnrob,

first of all thanks for creating these note types.

Please note, that they make AnkiDroid crash due to a size limit that Android enforces on String fields in a database: https://github.com/ankidroid/Anki-Android/issues/4241

**Comment by badlydrawnrob** [comment]
@leezu Hi Leonard, I'm glad you're using them! I haven't checked the repo in a while, it's getting more popular than I thought!

- Are you still having the issues with string fields?
- Are you using **[Highlight.js](https://github.com/badlydrawnrob/anki/blob/master/dist/themes/assets/css/README.md#automatic-syntax-highlighting-with-highlightjs)**?
    - I might have accidentally included it as default, and it's causing me some issues in iOS/OSX too.

It'd be helpful if you could let me know the above, I'm currently [considering alternative highlighting methods](https://github.com/badlydrawnrob/anki/issues/21). Without Highlight.js there shouldn't be any issues.

**Comment by badlydrawnrob** [comment]
@leezu Moving to another solution, using Pygments #21 — so should be no further issues.
