### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by andrewsanchez** [badlydrawnrob/anki#18]
Sorry for the dumb question, but could you please enlighten me to what should be obvious:  how do I install this?  I've managed to get it working by simply `git clone https://github.com/badlydrawnrob/anki.git` and importing anki-themes-1.0.0-beta-3.apkg.  Now the note types are available.  Is there a better way to do it, or is that just fine?  Is it better to `git clone https://github.com/badlydrawnrob/anki.git`  into a particular directory, e.g. ~/Documents/Anki/addons  ?

Thanks!  Looking forward to using this.

**Comment by badlydrawnrob** [comment]
@andrewsanchez Hi Andrew, this repo isn't an Anki addon, it's simple `Note Types` and `css` for your Anki decks. You can either clone it and keep things in sync, or manually download the [releases](https://github.com/badlydrawnrob/anki/releases). Bear in mind that from time to time, I'll be changing the fields and templates, which you'll have to (unfortunately) manually update.

Until I have a [live demo working](http://codepen.io/badlydrawnrob/pen/xwzyej), the safest way to check for any changes in the theme is to [follow this guide](https://github.com/badlydrawnrob/anki/blob/master/dist/deck/README.md).

Each time I create a new release, I create a duplicate version of the Note Types for the `.apkg` file which means when you import it, they shouldn't overwrite your existing Note Types or cards.

I haven't yet found a better method of updating your Anki Note Types and Cards than doing so manually. Which means:

- You'll have to keep an eye out for new fields (or changes to existing fields), and mirror these on your Note Types
- Copy and paste any template changes that occur.

Perhaps I should include a changelog for the next release.

**Comment by badlydrawnrob** [comment]
## To import new Anki Theme deck version:
1. Import direct into Anki profile
2. Check changes to testing Note Types
3. Manually import changes into old Note Types

* You can [optionally check out the new deck version](https://github.com/badlydrawnrob/anki/blob/master/dist/deck/README.md) in a dummy testing account for safety. The new deck version won't overwrite your old deck however, so the above steps are safe.
