### ISSUE TITLE
How Did You Solve iOS Highlight.js?

### ISSUE THREAD

**Issue by adeluccar** [badlydrawnrob/anki#19]
Hey @badlydrawnrob,

I have the following code in a template (Front Side):

```html
<link rel="stylesheet" href="_highlight.css">
<script src="_highlight.js"></script>

<div class="question">
{{Question}}
</div>

<pre><code class="language-{{Code Snippet Language}}">
{{Code Snippet}}
</code></pre>

<script>
hljs.initHighlighting.called = false;
hljs.initHighlighting();
</script>
```

Do you know why this works in Anki OS X and not in IOS?

![screen shot 2016-07-09 at 23 42 43](https://cloud.githubusercontent.com/assets/1455796/16711622/402258f2-4633-11e6-826e-c2105d9d5844.png)

**How did you fix it?**

Would really appreciate if you could help me out.
I downloaded your deck but couldn't figure it out myself.
Thanks! :

—Alberto

**Comment by adeluccar** [comment]
🆘

**Comment by badlydrawnrob** [comment]
@adeluccar Hi Alberto, I've been testing the Highlight.js script for a while now and honestly, I don't think Anki handles javascript well at all. I'm a complete novice with js, so perhaps someone else has a better method of handling Highlight.js (I've been looking for lighter examples, or different libraries, but no success yet) ...

The current method I'm using is the [shim repository via Bower](https://github.com/components/highlightjs), with the following code:

```js
var blocks = document.querySelectorAll('pre code:not(.hljs)');
Array.prototype.forEach.call(blocks, hljs.highlightBlock);
```

This works well on iOS, and partially in OSX (on the front card, but not on the reverse). The caveats are:

1. [Javascript must be inline](http://ankisrs.net/docs/manual.html#javascript), `src=` isn't supported (unless [using an addon](https://ankiweb.net/shared/info/1280253613))
2. iOS is really laggy at times, and it seems to [crash AnkiDroid](https://github.com/badlydrawnrob/anki/issues/17)
3. It really increases overall deck size and performance, as you can see in the below screenshot comparison (no media or scheduling have been included in the export):

<img width="640" alt="screen shot 2016-08-15 at 17 28 39" src="https://cloud.githubusercontent.com/assets/1176875/17669791/55d1d8be-630f-11e6-8675-489ebed566c8.png">

So, until Anki fully supports `src=` js on all devices, I'm beginning to think using something like [pygments](http://pygments.org/) is a far more practical solution, as there's backwards compatibility (albeit maintaining css for the code it outputs) and it can be safely swapped out for a js version if Anki eventually allows imports.

I've been using [Power format pack](https://ankiweb.net/shared/info/162313389) quite a bit, which really speeds up card creation. So I'll open another issue and see what people think.
