### ISSUE TITLE
AnkiDroid nightmode CSS

### ISSUE THREAD

**Issue by abers** [badlydrawnrob/anki#26]
The cards do not display that well when using nightmode in AnkiDroid. The Syntax field for example displays as dark grey on black background and the key point notes display as white on an off-white background. I only know the basics of CSS so was unsure what sections I would want to edit in order to have the cards display better when using nightmode.

**Comment by badlydrawnrob** [comment]
Hey @abers ...

- Could you add a few screenshots to this issue please? It'll give me a better idea of what needs changing.
- Could you confirm also [that this is the correct setup](https://ankiweb.net/shared/info/1496166067) (plugin) you're using?

> There is the class name `night_mode` when the night_mode is active (like in AnkiDroid)

**Comment by badlydrawnrob** [comment]
I feel this is something that can be solved on an "as-need" basis (override the css) — I don't think Anki (desktop) currently has a night-mode anyway.

**Comment by abers** [comment]
Apologies, I obviously missed the original reply. I was able to fix it by manually changing the CSS, was just flagging it in case there was an alternative solution.

**Comment by badlydrawnrob** [comment]
@abers No problem buddy,  It's not a super popular repo, so it's tricky to know where to spend time, and on what. I'm just pleasing myself for now, but if there are recurring requests I'd consider them.

If you give the [new version a spin](https://github.com/badlydrawnrob/anki/releases/tag/v2.0.0), I'd be grateful for feedback.

**Comment by badlydrawnrob** [comment]
@abers It's very late, but I've fixed this in the upcoming release. Hopefully looking ok in nightmode now. Let me know if you still make use of the tool :)
