### ISSUE TITLE
Card shows additional brackets after every field displayed

### ISSUE THREAD

**Issue by ferasodh** [badlydrawnrob/anki#57]
Check this sample
 What will each residents['key'] print out?**}**
Dictionaries**}**
d = {'key': value}**}**
Please check the attached image

![image](https://user-images.githubusercontent.com/1456776/103093053-deb13880-4601-11eb-97ef-d48d15544a59.png)

**Comment by hejiangda** [comment]
Hey,I find a way to fix it: 
![image](https://user-images.githubusercontent.com/11205949/103131764-04f7d680-46dd-11eb-96c9-edc07c449748.png)
The origin theme has three pair of braces just delete one pair of braces and the additional brackets disappeared!
![image](https://user-images.githubusercontent.com/11205949/103131930-d3cbd600-46dd-11eb-8f63-6c3f81e7219d.png)

**Comment by ferasodh** [comment]
Thanks @hejiangda this solves the issue
